### PR TITLE
Icon refresh and correction

### PR DESCRIPTION
**Pull request by ApostolosB**
The icon used now doesn't follow the design "spec" by jolla. To be exact the icon has sharp edges instead of rounded that are used in the SFOS template icons. I corrected this and polished the original a bit. A pretty similar icon over all.

### CODE REVIEW

**Comment by monich** [comment]
Good point about the corners.

**Comment by monich** [comment]
Shoudln't the QR code shadow be moved horizontally (e. g. to the left) by the same amount as it's moved down, to give it even more 3-D kind of look? Not that it would be really noticeable at a typical resolution. I'm not quite sure, what do you think?

**Comment by ApostolosB** [comment]
The gradient of the background colour is vertical and the shadow follows the same light pattern. I didn't want it to look too 3D when i was designing it. Hence the minimal shadow. I like it this way TBH.

**Comment by monich** [comment]
Ok, so be it!

**Comment by monich** [comment]
I squashed these commits into one, so you will have to rebase your master branch, I think.

**Comment by monich** [comment]
Thanks!

**Pull request merged**
