### PR TITLE
translation corrections for pt and de

### PR DESCRIPTION
**Pull request by amaretzek**

### CODE REVIEW

**Comment by monich** [comment]
Merged, thanks!

**Comment by amaretzek** [comment]
I found some typos, made some corrections, but i am totally lost on how to proceed... PRs don't seem right!

**Comment by monich** [comment]
Should I cherry-pick commit 0ff5bc8? It looks sane.

**Comment by monich** [comment]
I think I know why you're confused. You submitted this PR from your master branch. It may be OK if you know what you're doing, but generally it's a good idea to create a fresh branch for each PR. And this is a good example why.

I ended up squashing all your 6 commits into one commit 483c0a5. Now your master and my master have diverged. In order to pull updates from my master branch you need now to kill your master branch and create a fresh new one. If could be done like this:

```
# git branch -m master master.bak
# git remote add monich git@github.com:monich/sailfish-barcode.git
# git fetch monich
# git branch master monich/master
# git checkout master
# git push -u -f origin master
```

There may be other ways to achieve the same result but that's the first thing that comes to my mind.

If you submitted this PR from a branch, you wouldn't have to do it. You would do something like this:

```
# git checkout master
# git checkout -b mychanges
<make and commit your changes>
#  git push -u origin mychanges
```

Then submit your PR from `mychanges` branch and once it's merged just delete your branch and pull updates from master.

**Comment by amaretzek** [comment]
Hmm, thought 0ff5bc8 was already in. So, here starts my confusion. Yes, this should go in. I already made corrections on top of it. Will dig a bit to try to understand my confusion...

**Comment by monich** [comment]
> Hmm, thought 0ff5bc8 was already in. So, here starts my confusion. Yes, this should go in. I already made corrections on top of it. Will dig a bit to try to understand my confusion...

Yes,  0ff5bc8 is already in, this time I was confused :)

**Comment by amaretzek** [comment]
ok, will try that. I thought it would go like this: PR AM -> SM; SM merge; PR SM -> AM, so now they are in sync again; edit files, commit to AM; PR AM -> SM...

**Comment by amaretzek** [comment]
Monkey operator style copy paste of your commands bombs at "fetch", so I will have to learn....

**Comment by monich** [comment]
Submitting PRs from master branch isn't strictly a no-no. If I didn't squash then you could fast-forward your master branch and pull the merge commit and whatever may have been added on top of it.

The work-flow goes more like this: 1. AM change and commit 2. AM PR -> SM; 2. SM merge; 3. AM fast-forward and back to step one. But I squashed and you can't just fast-forward, you have to ditch your master branch and create a fresh new one.

With a branch it's almost the same except that every round starts with creating a branch and ends with deleting the branch.

**Comment by amaretzek** [comment]
ok, thanks. fetch problem was ssh keys...

**Pull request merged**
